# Asynchronous JavaScript: Promises, Async/Await, and AJAX

## Error Handling With try...catch

```jsx
const whereAmI = async function (country) {
	try {
		const pos = await getPosition();
		const { latitude: lat, longitude: lng } = pos.coords;
		const resGeo = await fetch(
			`https://geocode.xyz/${lat},${lng}?geoit=json`
		);
		const dataGeo = await resGeo.json();
		// console.log(dataGeo);
		if (!resGeo.ok) throw new Error("Problem getting location data");

		const res = await fetch(
			`https://restcountries.com/v3.1/name/${dataGeo.country}`
		);
		// console.log(res);
		if (!resGeo.ok) throw new Error("Problem getting country");

		const data = await res.json();
		console.log(data);
		renderCountry(data[0]);
	} catch (err) {
		console.error(err);
		renderError(`!! ${err.message} !!`);
	}
};
whereAmI();
console.log("First--");
```

---

[<PREV](./cjs221123.md) || [NEXT>](./cjs221124.md)
